### ISSUE TITLE
error：rayworker：

### ISSUE THREAD

**Issue by SHYang1210** [mveres01/deepq-grasping#1]

**Comment by SHYang1210** [comment]
Is it the environment version？

**Comment by mveres01** [comment]
Could be. Just cloned & confirmed it still works on my end with ray==0.6.6

You can try casting it to uint8 and it might get rid of the error, i.e. `state.transpose(2, 0, 1).astype(np.uint8)`, but fwiw the image size `(1, 1, 3)` also looks a little weird. Try casting and let me know?

**Comment by SHYang1210** [comment]
After I lowered the version of ray, the result can be run, and the result is similar to the picture on your GitHub. The size of the picture is limited, and you cannot zoom in and view it in the window. I don't understand the fwiw you mentioned.
